name: trekly
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Networking
  dio: ^5.4.1
  shared_preferences: ^2.5.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.0

  # Image
  image_picker: ^1.1.2

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Connectivity
  connectivity_plus: ^6.1.1

  # Permissions
  permission_handler: ^11.3.1

  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans Italic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf
    - family: OpenSans Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf